project:
  type: website
  output-dir: docs

website:
  title: "MLT Notes"
  repo-url: https://github.com/SherryS997/MLT_notes
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Home"
        contents: 
          - href: index.qmd
            text: Content
          - href: about.qmd
            text: About
      - section: "Notes"
        contents:
          - href: pages/Wk01.qmd
            text: Week-01
            title: Week-01
          - href: pages/Wk02.qmd
            text: Week-02
            title: Week-02
          - href: pages/Wk03.qmd
            text: Week-03
            title: Week-03
          - href: pages/Wk04.qmd
            text: Week-04
            title: Week-04
          - href: pages/Wk05.qmd
            text: Week-05
            title: Week-05
          - href: pages/Wk06.qmd
            text: Week-06
            title: Week-06
          - href: pages/Wk07.qmd
            text: Week-07
            title: Week-07

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true



